### ISSUE TITLE
Support CONJUR_AUTHN_TOKEN_FILE configuration option

### ISSUE THREAD

**Issue by kgilpin** [conjurinc/summon-conjur#11]
This is used for reading the auth token from a file, which is continually refreshed by another process.

For example - https://github.com/conjurinc/api-ruby/blob/c442d33862d9f1bfe51e3895bb781c0068a2e891/lib/conjur/base.rb#L152

**Comment by ghost** [comment]
We need to update the config struct (and maybe some of the parsing logic, but there are tests!)

https://github.com/conjurinc/summon-conjur/blob/master/config.go#L12
https://jenkins.conjur.net/job/summon-conjur/

**Comment by ghost** [comment]
`CONJUR_AUTHN_TOKEN_FILE ` is now in master, docs: https://github.com/cyberark/summon-conjur#configuration.

Closing this issue since it was resolved in #13.
