### ISSUE TITLE
Explicit directions for using Summon with `summon-conjur` provider for both Conjur 4.9 and 5.x

### ISSUE THREAD

**Issue by jvanderhoof** [conjurinc/summon-conjur#14]
We just helped Joe install Summon and Summon-Conjur for a Jenkins demo.  His struggle illustrated the lack of explicit documentation, particularly with the `summon-conjur` version he needed to use to communicate with Conjur 4.9.  

To address this, let's add examples of downloading and installing Summon and the Summon-Conjur to the README.  We should also document loading a variable value from Conjur.  There should be two version: 4.9 and 5.x.  For simplicity of example, `env` would make a good child process:

```sh
$ summon env
```

**Comment by ghost** [comment]
This is a great idea! `summon env` is basically 'hello world'

**Comment by doodlesbykumbi** [comment]
@jvanderhoof are you happy to close this issue ? the PR above should address it^

**Comment by jvanderhoof** [comment]
I really think we need an explicit example of how to install and configure Summon with the Conjur provider for both CE and the EE editions.  Think about the steps you ran through with Joe to help him get everything working.  Noting which version work for which Conjur version and where they should be installed.

**Comment by PeteW** [comment]
Right now I am running in to an issue with summon 
>summon -p summon-conjur env
**Error fetching variable XXX: exit status 1: Authentication: 404 Not Found**
I'll eventually work my way through it.

The lack of verbose/debug output combined with the light documentation makes it challenging for us newcomers to understand all the conventions. A troubleshooting section would be helpful thats for sure

**Comment by PeteW** [comment]
followup
Turns out my issue was a version incompatibility between summon-conjur and our conjur server. There is enough significant changes between versions where publishing some sort of client/server compatibility matrix would save end-users like myself a good amount of time in trying to understand 404 errors like this.

**Comment by szh** [comment]
I'm going to close this since we're removing support for Conjur v4.
