### ISSUE TITLE
Summon does not use conjur-cli configuration files

### ISSUE THREAD

**Issue by jeniaSakirko** [conjurinc/summon-conjur#15]
I configured the conjur-cli to use `/etc/conjur.conf` and `/etc/conjur.identity` and it worked but when I try to use summon-conjur I get `Environment variables satisfying at least one authentication strategy must be provided!`

**Comment by doodlesbykumbi** [comment]
The latest iteration of summon-conjur that supports v5 does not currently support machine identity files. it only accepts environment variables. so you have to extract the machine identify from the files of a conjurized host and set the appropriate environment variables.

Here's the example from my ansible-role-conjur PR showing both authentication strategies.

```
export CONJUR_IDENTITY_PATH=/etc/conjur.conf
export CONJUR_ACCOUNT=$(awk '/account:/ {print $2}' $CONJUR_IDENTITY_PATH)
export CONJUR_APPLIANCE_URL=$(awk '/appliance_url:/ {print $2}' $CONJUR_IDENTITY_PATH)
CONJUR_NETRC_PATH=$(awk '/netrc_path:/ {print $2}' $CONJUR_IDENTITY_PATH)
: ${CONJUR_NETRC_PATH:="/etc/conjur.identity"}

# Login Credentials

export CONJUR_AUTHN_LOGIN=$(awk -v CONJUR_APPLIANCE_URL=$CONJUR_APPLIANCE_URL '$0 ~ CONJUR_APPLIANCE_URL {f=1} f && /login/ {print $2;f=0}' $CONJUR_NETRC_PATH)
export CONJUR_AUTHN_API_KEY=$(awk -v CONJUR_APPLIANCE_URL=$CONJUR_APPLIANCE_URL '$0 ~ CONJUR_APPLIANCE_URL {f=1} f && /password/ {print $2;f=0}' $CONJUR_NETRC_PATH)

# Token File Credentials

function finish {
    echo "Cleaning up..."
    kill $CONJUR_AUTHN_TOKEN_FILE_PID
    echo "All done."
}
trap finish EXIT
while true; do echo $(conjur authn authenticate) > /tmp/CONJUR_AUTHN_TOKEN_FILE ; sleep 2; done &
export CONJUR_AUTHN_TOKEN_FILE_PID=$!
export CONJUR_AUTHN_TOKEN_FILE=/tmp/CONJUR_AUTHN_TOKEN_FILE
```

**Comment by ghost** [comment]
we should maintain v4 and v5 compatibility with this provider, if possible. i think it should be. otherwise we're introducing confusion into the workflow, which provider to use?

**Comment by doodlesbykumbi** [comment]
@dustinmm80 I agree. I'm working on adding support for v4 and support for autoloading configuration from machine identity files.
