### ISSUE TITLE
Does not read CONJUR_SSL_CERTIFICATE from environment

### ISSUE THREAD

**Issue by dsbyrne** [conjurinc/summon-conjur#3]
As documented in the link below, I should be able to provide CONJUR_SSL_CERTIFICATE as an environment variable. Instead, this provider looks for a path to the certificate on disk (CONJUR_CERT_FILE).

https://developer.conjur.net/key_concepts/machine_identity.html

**Comment by ghost** [comment]
Addressed in PR https://github.com/conjurinc/summon-conjur/pull/7
