### ISSUE TITLE
Fails if .netrc does not exist

### ISSUE THREAD

**Issue by dsbyrne** [conjurinc/summon-conjur#4]
`open /app/.netrc: no such file or directory`

A .netrc file must be provided even if a Conjur identity is provided through the environment, eliminating the need for this file.

**Comment by dividedmind** [comment]
Are you sure it fails? It seems to me it only prints the message. Which is a bug, too, I guess ;)

**Comment by ghost** [comment]
Fixed in PR https://github.com/conjurinc/summon-conjur/pull/6
