### ISSUE TITLE
On Windows, use (and prioritize) Windows Generic Credentials instead of env variables or `.netrc`

### ISSUE THREAD

**Issue by Jishin85** [conjurinc/summon-conjur#54]
## All of our Modules for tools that can work with Windows should save credentials inside the Generic Credentials store

I would like `summon-conjur` to be able to use Generic Credentials (Credential Manager > Windows Credentials > Generic Credentials) in a Windows machine rather than using files or env vars. Exposing those with a PowerShell script would potentially leave scripts too much power over that Windows box, reducing desired security.

## Describe the solution you would like

If on Windows, use the [GetGenericCredential](https://pkg.go.dev/github.com/danieljoos/wincred?tab=doc#GetGenericCredential) method to retrieve username and API key, prioritizing this over .netrc and environmental variables.

**Comment by sgnn7** [comment]
@Jishin85 Thank you for suggesting this approach! 

PS: I may do a bit of editing on your post to make it clear what is desired

**Comment by izgeri** [comment]
@sgnn7 is it possible this could be a generic approach that would benefit mac / linux users too? I am wondering if it would be possible to optionally configure summon to use a credential provider for the summon provider connection config.

I know that sounds kind of cyclical, but I like the idea of using my osx keyring or lastpass to provide my conjur creds to summon to retrieve my dev conjur secrets.

**Comment by sgnn7** [comment]
@izgeri Ideally yes that would be desired but the problem is that each OS has their own implementation of "secure credential store" and we would need either separate providers for each or a big omni-bus package to abstract these ops.

**Comment by izgeri** [comment]
my weirdo suggestion is that we use the existing implemented secrets providers

summon-conjur, summon-keyring, etc

the users can specify which one to use

**Comment by sgnn7** [comment]
If we make a generic one, we can use the same one here _and_ in secretless broker though :)
