### ISSUE TITLE
Documentation is missing path for conjur identity files on Windows

### ISSUE THREAD

**Issue by whip113** [conjurinc/summon-conjur#70]
## Summary
The documentation for how summon-conjur is configured is missing details for windows. Specifically, that the path to the identity files is `C:\Windows\conjur.conf` and `C:\Windows\conjur.identity`.

## Steps to Reproduce
NA

## Expected Results
The documentation should include specifics for all supported OS classes.

## Reproducible
   * Always 

## Version/Tag number
Latest (0.5.3)

**Comment by sgnn7** [comment]
Sadly, `C:\Windows\conjur.identity` is not something that works [due to an upstream bug](https://github.com/cyberark/conjur-api-go/issues/53) but the other info can be updated.
