### ISSUE TITLE
-v flag does not generate verbose debug output in summon-conjur v0.5.3

### ISSUE THREAD

**Issue by jodyhuntatx** [conjurinc/summon-conjur#77]
## Summary
v0.5.2 generates verbose debug output w/ the -v flag. v0.5.3 does not

## Steps to Reproduce
# /usr/local/lib/summon/summon-conjur -v <secret-name>

## Expected Results
DEBUG Config from /etc/conjur.conf: {Account:dev ApplianceURL:https://conjur-master-mac:443 NetRCPath:/etc/conjur.identity SSLCert: SSLCertPath:/etc/conjur-dev.pem Https:false V4:false}

DEBUG Failed reading /root/.conjurrc, open /root/.conjurrc: no such file or directory

DEBUG Config from environment: {Account: ApplianceURL: NetRCPath: SSLCert: SSLCertPath: Https:false V4:false}

DEBUG Final config: {Account:dev ApplianceURL:https://conjur-master-mac:443 NetRCPath:/etc/conjur.identity SSLCert: SSLCertPath:/etc/conjur-dev.pem Https:false V4:false}

DEBUG 200 POST https://conjur-master-mac:443/authn/dev/host%2Fclient%2Fnode/authenticate map[Content-Type:[text/plain]]
DEBUG req: &{Method:GET URL:https://conjur-master-mac:443/secrets/dev/variable/cicd-secrets%2Ftest-db-username Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Authorization:[Token token="eyJwcm90ZWN0ZWQiOiJleUpoYkdjaU9pSmpiMjVxZFhJdWIzSm5MM05zYjNOcGJHOHZkaklpTENKcmFXUWlPaUkzTWpSbU5HUXhaVE13WkRVeVlUbGpaalkxTW1RME5qQm1PRFl5WmpBME0yRXlOalF5TXpRNU56UmxPRGt5TURNd1l6QXhOelUxWVRneE9ERTBZV0UzSW4wPSIsInBheWxvYWQiOiJleUp6ZFdJaU9pSm9iM04wTDJOc2FXVnVkQzl1YjJSbElpd2lhV0YwSWpveE5qRTBOakkyTnpFM2ZRPT0iLCJzaWduYXR1cmUiOiJrdURKUXpGZlVNOHlsWHdVaGdNU0FNTFMyOXRYYk5UNWdDZmFVVXo4WDNTOVJyejNDbzhqdmRTb0hWaDFSTUNqQWpqMEtCd1ZTdFBOeXFobkRIOXFvU0EwVTQwWW9rT3I0MXJ0TWx1VW9ZXzY4NHpkcHhIa0RULThjRUlRc1BIY1BDTVh3NjdkVTQwZzRRUWxEXzlzczlkSkllcGk1TDl5dlhjSU5wRlpFV0szVElJVENqd0xyM0FnMUFEQkUzbHdJdmg0MEJzMlBSNXI0M0VpWWFpY2FtVmZnakUxV1l5UTBWQnZra1VSaXQwZ0xfWGU3UlR5NXlKZF9RQXpoa1E2cTBHeUNZeVNEdTNMcFhNYlF3b04wazVVQkNaaVVXbWxPZzdlRnNkNjFTay0wQ1FwWHlXSVp0RndpRm1rSWJzVjVOUXF0MmIwOHd3UlJ1ZHJIdzRpVUlpemZTLVIydndvWUMxRDJCMkpneUdMX2RrRjZoeDR2TklkUU5scmZ4Y18ifQ=="]] Body:<nil> GetBody:<nil> ContentLength:0 TransferEncoding:[] Close:false Host:conjur-master-mac:443 Form:map[] PostForm:map[] MultipartForm:<nil> Trailer:map[] RemoteAddr: RequestURI: TLS:<nil> Cancel:<nil> Response:<nil> ctx:<nil>}

DEBUG 200 GET https://conjur-master-mac:443/secrets/dev/variable/cicd-secrets%2Ftest-db-username map[Authorization:[Token token="eyJwcm90ZWN0ZWQiOiJleUpoYkdjaU9pSmpiMjVxZFhJdWIzSm5MM05zYjNOcGJHOHZkaklpTENKcmFXUWlPaUkzTWpSbU5HUXhaVE13WkRVeVlUbGpaalkxTW1RME5qQm1PRFl5WmpBME0yRXlOalF5TXpRNU56UmxPRGt5TURNd1l6QXhOelUxWVRneE9ERTBZV0UzSW4wPSIsInBheWxvYWQiOiJleUp6ZFdJaU9pSm9iM04wTDJOc2FXVnVkQzl1YjJSbElpd2lhV0YwSWpveE5qRTBOakkyTnpFM2ZRPT0iLCJzaWduYXR1cmUiOiJrdURKUXpGZlVNOHlsWHdVaGdNU0FNTFMyOXRYYk5UNWdDZmFVVXo4WDNTOVJyejNDbzhqdmRTb0hWaDFSTUNqQWpqMEtCd1ZTdFBOeXFobkRIOXFvU0EwVTQwWW9rT3I0MXJ0TWx1VW9ZXzY4NHpkcHhIa0RULThjRUlRc1BIY1BDTVh3NjdkVTQwZzRRUWxEXzlzczlkSkllcGk1TDl5dlhjSU5wRlpFV0szVElJVENqd0xyM0FnMUFEQkUzbHdJdmg0MEJzMlBSNXI0M0VpWWFpY2FtVmZnakUxV1l5UTBWQnZra1VSaXQwZ0xfWGU3UlR5NXlKZF9RQXpoa1E2cTBHeUNZeVNEdTNMcFhNYlF3b04wazVVQkNaaVVXbWxPZzdlRnNkNjFTay0wQ1FwWHlXSVp0RndpRm1rSWJzVjVOUXF0MmIwOHd3UlJ1ZHJIdzRpVUlpemZTLVIydndvWUMxRDJCMkpneUdMX2RrRjZoeDR2TklkUU5scmZ4Y18ifQ=="]]

## Actual Results (including error logs, if applicable)
returns only the value of the secret - no verbose output.

# /usr/local/lib/summon/summon-conjur -v cicd-secrets/test-db-username
ThisIsTheTESTDBuserName

## Reproducible
   * [ ] Always 
   
## Version/Tag number
v0.5.3

## Environment setup
using /etc/conjur* files for config, identity & cert.

**Comment by doodlesbykumbi** [comment]
Thanks for submitting the issue @jodyhuntatx. Got a [PR](https://github.com/cyberark/summon-conjur/pull/78) up to fix this in the next release
